### ISSUE TITLE
Migrate from current ckan instance to new setup (2014)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/dataportals.org#23]
- [x] #3 - shut down submissions to old instance
  - As this is not easy we may just hope no-one submits and then move this to e.g. old.datacatalogs.org
- [x] Pull data and import into gdoc (repeat process from last time)
  - [x] #24 - metadata structure for new DB
  - [x] #25 Do the migration of data
- [x] Switch sites - DNS etc
